services:
  shell:
    build:
      context: .
      dockerfile: shell.Dockerfile
    volumes:
      - .:/.docker-image-diff/
      - ./output/:/.docker-image-diff-output/
    environment:
      - OUT=/.docker-image-diff-output
    working_dir: /.docker-image-diff/
